language: python
sudo: required
services:
- docker
deploy:
  provider: pypi
  user: richford
  password:
    secure: ne6NMwp7HVEuErQ5c/CM9CFx6wrZZwVoyXs7equdrN5qK+5dczM9rNFpZkYAORCVHefzCIDQ8Zs438qhY7JUAfnDqRHf2N5uwYi7vPNNm8CxlYDkfqmm+0BaV7Mr9Pn90fWrPZR4P65TRALSG84l1/5NW08HmmXCPg5kjuxlA0AW0+u/1TM4qrowKE0rKe7Ug2F9nI9EaaXQHGjBNHK6B5/K5ceIGnP3YhiKlFSAMqu3/n2oT8o1XJs4htf070YGQ26H2+LBWnidkNkgoXVLvlqXPkBbo56FYsxwiAD0Klsz2hMneH5smKwPU/xRHFUpj4wNlCwV6b1aMH95q+RoUVysHlSMfjpgqh8VZuvc+D0Vw1ex1t2Bonu/akxgpE3neA/F2Hza+fNyGh4i+Lx3/8Rlt4IT8QUVz/frHmkNudvq9VDBdds6EIRNFVnVEKHbLbwPd4A4WjW5ZqwTNTvGA6b+FpNJEeHpau1g1cw1MwIUZGySoZO1woFqVNpeRL9UXnL9r1ejcMZb7TtBBj5zdqe282tAQmpNFypyFiTcO9UqNX9DkyvvF/tDNT3v+O0YKYzOrzbAhnxq2JJpRv02u3K4+uVOlwTPbRMsRuo0NqSIglzaHaeUy8myvEV9Ol43uybD6hGZVmmS6rk4wGs+ThwcVpz8GAB45duxNsH+1wU=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: richford/cloudknot
env:
  global:
  - secure: K2EJqa9df2Pur0lZWyTIvXiRfhyrAtgxOxQ0RfP6kyroCTLXQN6JWncB4RPrfjF37iFyx4QN+B4VGDRvmxS6d17hq+3BdMmQDy7W2JcXBcdQXRj1YKvGvCNOaH1AXRgshljcx/2AuT3afpe6mJvxaKx/Uc5zY8fimy0AlPVh7kTaZ5txcfglMl/KSzP+6Iy2Zh0ubxrPAitxHkVfBlo8Z/c+3+c6cKBHX5FDA/M5qJv8LaLSIFMG5464M0qqMknW/xkTey+9Ma4Q9JJD/6/9Dm1OwTq46FuNreSXBSAxK55Lf/W2sRy/PczXQmIDKRVaUUpfZEPdndQMNsfvepbZbvlGBY9c9Yq3IB2Dnh4QXxv+SjmNCnW2gM9leGzWd+a1kTGc8Fo7px7VUhZ2Oo5pmrvHMOrldT3MJ8CUqfyp8boChIqVwFL2a1AvFNnou8/BSH7Yjm5jipTQLjmC3xO3f+v1rYo2oFt7rVbHOw53qLcge6DF3ha6EclQhE9SSebxEXTTC//by9Rfk0KHYRCrBbCk9FEwOAprAfa9LvAAzahsIsxOoMqGBDJXj/6YrgCGrqD8Bp+z1zWRDQDDqDED+QpCXq5H52LSot0F/8z6n0w3HRHjjtfEMhdWlP1AlgmypkVB8Y/BdjbFv3qrFBo9GDWXeoskVpg2Mtg6Cyt94hI=
python:
- '3.6'
install:
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .[dev]
script:
- flake8 `find . -name \*.py | grep -v setup.py | grep -v
  version.py | grep -v __init__.py | grep -v /doc/`
- mkdir ~/config_files
- printf "[aws]\nconfigured = True\n" > ~/config_files/cloudknot
- travis_wait 50 py.test --pyargs cloudknot --cov-report term-missing --cov=cloudknot
after_success:
- coveralls -v
- |
  if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
    pip install sphinx sphinx-gallery
    set -e;
    cd doc;
    make clean;
    make html;
    cd ..;
    pip install doctr;
    doctr deploy . --built-docs doc/_build/html;
  fi
